---
title: "Assignment-1"
author: "Buğra Sarıkaya"
date: "17/01/2022"
output: word_document
---
``` {r setup, include = FALSE}
library(tidyverse)
library(knitr)
opts_chunk$set(warning = FALSE, message = FALSE)
```
# Q1A:
``` {r echo = FALSE}
cat("There are ", nrow(filter(starwars, starships != "character(0)")), " characters who have at least one starship.\n")
kable(summarize(mutate(subset(starwars, subset = (starships != "character(0)")), ships = sapply(starships, toString)), name, ships, count = lengths(starships)) %>% arrange(desc(count)))
```
# Q2A:
``` {r echo = FALSE}
kable(starwars %>% group_by(eye_color) %>% summarize(count = n()) %>% arrange(desc(count)))
```
# Q3A:
``` {r echo = FALSE}
kable(starwars %>% group_by(species) %>% summarize(count = n(), avg = mean(birth_year, na.rm = TRUE)) %>% arrange(desc(avg)) %>% slice(1:3))
```
# Q4A:
``` {r echo = FALSE}
starwars_2 <- mutate(starwars, height = as.numeric(height), mass = as.numeric(mass), birth_year = as.numeric(birth_year), films = sapply(films, toString), vehicles = sapply(vehicles, toString), starships = sapply(starships, toString))
starwars_2 <- rbind(starwars_2, list("Buğra Sarıkaya", 170, 60, "black", "fair", "brown", 26, "male", "masculine", "Dathomir", "Human", "Return of the Jedi", "Tsmeu-6 personal wheel bike", "Jedi Interceptor"))
kable(filter(starwars_2, name == "Buğra Sarıkaya"))
```
# Q5A:
``` {r echo = FALSE}
starwars_2 <- mutate(starwars_2, BMI = mass / ((height / 100) * (height / 100)), weight_status = ifelse(BMI < 18.5, "underweight", ifelse(BMI >= 18.5 & BMI <= 24.99, "healthy", ifelse(BMI >= 25.0 & BMI <= 29.99, "overweight", "obese"))))
kable(starwars_2 %>% slice(1:2))
```
# Q6A:
``` {r echo = FALSE}
ggplot(filter(starwars_2, birth_year < 100), aes(x = weight_status, y = birth_year)) + geom_boxplot()
```

# Q7A:
``` {r echo = FALSE}
ggplot(starwars_2, aes(x = birth_year, y = BMI)) + geom_point() + geom_smooth()
ggplot(filter(starwars_2, birth_year < 100 & BMI < 100), aes(x = birth_year, y = BMI)) + geom_point() + geom_smooth()
```